### ISSUE TITLE
scSeq pipeline only worked half way

### ISSUE THREAD

**Issue by dam39** [hbc/tutorials#1]
Hi hbc staff,
I tried running the single cell seq pipeline in bcbio-nextgen as the tutorial explained, and it worked pretty well. At some point though, I think an operation timed out and was killed and so the pipeline never worked till the end. I have a lot of the intermediate files, and the job died 2 days in, so I don't want to start from the top. Is there anyway to figure out what the exact commands executed by the pipeline are? I can't seem to figure that out. All I know are the commands that ran as they are in the log files. Maybe a log file of a job that ran to completion would help.
Thanks a lot!
Doaa

**Comment by naumenko-sa** [comment]
Hi @dam39 !

You can see the commands in `project/work/log/bcbio-nextgen-commands.log`
Please post bcbio issues here:
https://github.com/bcbio/bcbio-nextgen/issues

Sergey
